jenkinsci/workflow-step-api-plugin

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java

See https://github.com/jenkinsci/workflow-cps-plugin/pull/3 for discussion.
@reviewbybees

[JENKINS-26156] Fixing BodyInvoker.withDisplayName Javadoc

---

src/main/java/org/jenkinsci/plugins/workflow/util/StaplerReferer.java

Needed for https://github.com/jenkinsci/workflow-cps-plugin/pull/12.
@reviewbybees

[JENKINS-31831] Make referer URL pattern more permissive

---

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java

Used by https://github.com/jenkinsci/workflow-cps-plugin/pull/25.
@reviewbybees

[JENKINS-31842] Define status of a StepExecution

---

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java

Use Throwable.addSuppressed

---

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java

If a FlowInterruptedException has a cause and/or suppressed exceptions, print them

---

src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java

[Reference](https://groups.google.com/d/msg/jenkinsci-dev/34AKdC0SARM/nxDgHUFoAAAJ)
@reviewbybees

Documenting that StepDescriptor.functionName should start with a lowercase letter

---

src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java

[JDK-8075793](https://bugs.openjdk.java.net/browse/JDK-8075793)
@reviewbybees

Placate the JDK 9 compiler

---

src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java

[JENKINS-39275](https://issues.jenkins-ci.org/browse/JENKINS-39275)
@reviewbybees

[JENKINS-39275] Bound time taken by StepExecution.getStatus

---

pom.xml

Downstream of https://github.com/jenkinsci/plugin-pom/pull/38.
@reviewbybees esp. @stephenc

New way of building a test JAR

---

pom.xml

Pick up https://github.com/jenkinsci/plugin-pom/pull/39

---

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java

FlowInterruptedException was sometimes recording & printing CauseOfInterruption’s that were already attached to the build

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
src/main/java/org/jenkinsci/plugins/workflow/util/StaplerReferer.java

Downstream of https://github.com/jenkins-infra/pipeline-library/pull/3.
cf. [INFRA-1052](https://issues.jenkins-ci.org/browse/INFRA-1052)
@reviewbybees

Jenkinsfile

---

README.md
src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java

Improving Javadoc for StepDescriptor.getRequiredContext

---

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java

Trying to clarify some Javadoc

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
src/test/java/org/jenkinsci/plugins/workflow/steps/StepDescriptorTest.java

Part of [JENKINS-37324](https://issues.jenkins-ci.org/browse/JENKINS-37324) and upstream of:
https://github.com/jenkinsci/workflow-api-plugin/pull/26
https://github.com/jenkinsci/workflow-cps-plugin/pull/98

[JENKINS-37324] API to format Step arguments to string

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl.java
src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java
src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplRestartTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java

Really I just wanted to bump up the parent POM to make sure we have picked up https://github.com/jenkinsci/jenkins-test-harness/pull/35, but figured I would look around for other warnings and TODOs while I was here.
@reviewbybees

Miscellaneous cleanups

---

src/main/java/org/jenkinsci/plugins/workflow/steps/EnvironmentExpander.java

Stemming from https://github.com/jenkinsci/pipeline-stage-step-plugin/pull/10 in particular.
Probably needs tests somewhere. =)
cc @reviewbybees

Provide an API for an EnvironmentExpander of constant string->string map

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplRestartTest.java

[JENKINS-26148](https://issues.jenkins-ci.org/browse/JENKINS-26148)
@reviewbybees

[JENKINS-26148] Default implementation of StepExecution.stop

---

src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java

Otherwise the step just hangs. Nothing in the build log, nothing in the system log, nothing in the physical or virtual thread dumps—nothing. Oops.
@reviewbybees

Catch anything thrown by SynchronousNonBlockingStepExecution.run

---

.gitignore
.mvn/extensions.xml
.mvn/maven.config
pom.xml

[Guide](https://github.com/jenkinsci/pom/blob/master/incrementals.md#enabling-production-of-incrementals)

Preparing for Incrementals

---

pom.xml

Follows up #34, as noted in the [guide](https://github.com/jenkinsci/incrementals-tools/blob/master/README.md#running-maven-releases).

Reincrementalified

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java
src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/util/StaplerReferer.java
src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java

Amends https://github.com/jenkinsci/workflow-step-api-plugin/pull/38 to pick up the behavioral change in https://github.com/jenkinsci/workflow-cps-plugin/pull/268.

[JENKINS-49337] GeneralNonBlockingStepExecution follow-up

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java

Downstream of https://github.com/jenkinsci/structs-plugin/pull/43.

CustomDescribableModel would supersede less general methods in StepDescriptor

---

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java
src/test/java/org/jenkinsci/plugins/workflow/steps/StepExecutions.java

Can be used to address [JENKINS-41854](https://issues.jenkins-ci.org/browse/JENKINS-41854) and related problems.

[JENKINS-41854] DynamicContext

---

CHANGELOG.md

I am planning on releasing this today.

Add 2.22 release notes

---

.mvn/extensions.xml
Jenkinsfile
pom.xml

Example of https://github.com/jenkinsci/incrementals-tools/pull/16.

[JENKINS-58716] Using gitHubRepo

---

CHANGELOG.md

update changelog for 2.23

---

CHANGELOG.md

add 2.24 to changelog

---

CHANGELOG.md
README.md

clean up readme and changelog

---

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java
src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java
src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/steps/EnvironmentExpander.java
src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/MissingContextVariableException.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepEnvironmentContributor.java
src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
src/main/java/org/jenkinsci/plugins/workflow/util/StaplerReferer.java

EOL JSR 305

---

pom.xml

https://github.com/jenkinsci/workflow-step-api-plugin/pull/78#issuecomment-1006164196

Update parent, `bom`, baseline

---

src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java

Rather than "slave" use "agent"
~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Make a comment more inclusive
