src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
API needed for [JENKINS-26107](https://issues.jenkins-ci.org/browse/JENKINS-26107).
@reviewbybees esp. @kohsuke
=> [JENKINS-26107] StepContext.hasBody

pom.xml, src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
Documenting the contract of a meta step
=> [JENKINS-29922] mark meta step

pom.xml, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepExecutionImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java, src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplRestartTest.java
[JENKINS-39134](https://issues.jenkins-ci.org/browse/JENKINS-39134)
@kohsuke any clue?
@reviewbybees
=> [JENKINS-39134] CreationException thrown for block-scoped executions injecting step with no-arg ctor

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepExecutionImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java, src/main/java/org/jenkinsci/plugins/workflow/steps/MissingContextVariableException.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepContextParameter.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java, src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java, src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
Follows up #14 by deprecating the Guice-based `Step` infrastructure.
Downstream PRs to follow.
@reviewbybees esp. @kohsuke
=> [JENKINS-39134] Deprecate injection

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepExecutionImpl.java
=> [JENKINS-40909] Steps which traditionally extended AbstractStepExecutionImpl cannot just switch the superclass

src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
[JENKINS-41551](https://issues.jenkins-ci.org/browse/JENKINS-41551)
Related to, but distinct from, #16. Goes further than #12.
@reviewbybees
=> [JENKINS-41551] Do not call even getStatusBounded from toString

src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
Looking at an actual log file where this is logged, there are dozens of stack traces like
```
… WARNING o.j.p.w.steps.StepExecution#getStatusBounded: failed to check status of org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution@…
java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at org.jenkinsci.plugins.workflow.steps.StepExecution.getStatusBounded(StepExecution.java:135)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDump$ThreadInfo.<init>(CpsThreadDump.java:49)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDump$ThreadInfo.<init>(CpsThreadDump.java:29)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDump.from(CpsThreadDump.java:139)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.getThreadDump(CpsThreadGroup.java …
```
=> Downgrade logging from getStatusBounded

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
Downstream of https://github.com/jenkinsci/jenkins/pull/1485.
@reviewbybees
=> Use Functions.printThrowable to provide more legible stack traces in 2.43+

src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
It was a mistake to mark this `@CheckForNull` when in fact the only caller is `ArgumentsAction.getStepArgumentsAsString`, which calls it on a map which is never null. There is just no compelling reason why it would be null, and an extra null check imposes a burden on implementors.
(Ironically, prior to https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/47, the only override was [this one](https://github.com/jenkinsci/workflow-cps-plugin/blob/c69e3862bf26ac122dbc26345f1bb73b906c6824/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java#L60-L61), which assumed it was nonnull!)
@reviewbybees
=> The parameter to argumentsToString should be @Nonnull

src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
[JENKINS-48115](https://issues.jenkins-ci.org/browse/JENKINS-48115)
While we can work around this in Declarative, cases like https://github.com/jenkinsci/jira-steps-plugin/blob/master/src/main/java/org/thoughtslive/jenkins/plugins/jira/steps/NewComponentStep.java#L50 end up reporting as metasteps of literally any existing symbol. So let's restrict `allMeta()` to only include steps with both `d.isMetaStep()==true` and `Describable.class.isAssignableFrom(d.getMetaStepArgumentType())`.
cc @reviewbybees
=> [JENKINS-48115] Don't include non-Describables as metasteps

src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
…so that we properly handle `FlowInterruptedException`. Follows up #30 and works analogously to https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/50 and part of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/67. Needed for https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/41: otherwise,
```groovy
timeout(5) {
archiveArtifacts '…'
}
```
will cause the build status to be `FAILURE` since an `InterruptedException` will be thrown and be treated as the terminal exception, while the `FlowInterruptedException` which captured the `ABORTED` status and reason for interruption is discarded.
=> SynchronousNonBlockingStepExecution.stop should call super

pom.xml, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
See [JENKINS-53305](https://issues.jenkins-ci.org/browse/JENKINS-53305) and jenkinsci/workflow-basic-steps-plugin#69 for related discussion. 
This PR uses `ClassLoaderSanityThreadFactory` for `SynchronousNonBlockingStepExecution` so that the context class loader for all new threads is automatically set to the class loader for `ClassLoaderSanityThreadFactory`. If the root cause of the problem in JENKINS-53305 is that the class loader is somehow null coming into the step execution before we create a new thread in `SynchronousNonBlockingStepExecution`, then this would fix the problem.
If the root cause is instead that some code is incorrectly modifying the class loader inside of `SynchronousNonBlockingStepExecution#run`, then this would not fix the issue, as the threads in the pool may be …
=> [JENKINS-53305] Use ClassLoaderSanityThreadFactory for SynchronousNonBlockingStepExecution

.mvn/extensions.xml, Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java, src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/MissingContextVariableException.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecutionTest.java, src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
Utility to solve issues like [JENKINS-49337](https://issues.jenkins-ci.org/browse/JENKINS-49337).
=>  [JENKINS-49337] GeneralNonBlockingStepExecution

src/main/java/org/jenkinsci/plugins/workflow/steps/EnvironmentExpander.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepEnvironmentContributor.java
See [JENKINS-51170](https://issues.jenkins-ci.org/browse/JENKINS-51170), jenkinsci/workflow-cps-plugin#229, and jenkinsci/workflow-support-plugin#62.
This allows plugins to provide environment variables scoped to a single
workflow step.
Patches for workflow-support and workflow-cps are prepared.
I am not sure how to make sure that implementors of the ExtensionPoint can depend on recent enough versions of workflow-support and workflow-cps to actually execute the contributors.
=> [JENKINS-51170] add StepEnvironmentContributor ExtensionPoint

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
Tested against https://github.com/jenkinsci/kubernetes-plugin/pull/461/commits/eed014f57d1f84b9cc7297614483c0b347c255c2; avoids an ugly stack trace.
=> FlowInterruptedException.handle should recurse on nested/suppressed exceptions

src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java
Has been successfully used in releases of `kubernetes` and `workflow-durable-task-step` for a while now.
=> Remove beta marking from DynamicContext

src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
Reasoning: stopCause is used from multiple threads. In order to guarantee that task thread sees updated value, JMM requires field to be volatile.
=> Make {Synchronous,General}NonBlockingStepExecution.stopCause volatile

pom.xml, src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecutionTest.java
See [JENKINS-58878](https://issues.jenkins-ci.org/browse/JENKINS-58878).
**Update**: fix is in https://github.com/jenkinsci/workflow-cps-plugin/pull/335, I'll update this PR once I have an incremental build.
---
Just adding an ignored test for now while I try to figure out the right way to fix the problem. Here's a bad fix:
```diff
--- a/src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java
+++ b/src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java
@@ -74,6 +74,7 @@ public abstract class GeneralNonBlockingStepExecution extends StepExecution {
threadName = Thread.currentThread().getName();
try {
try (ACLContext acl = ACL.as(auth)) {
+                    Thread.sleep(10L);
block.run();
}
} catch (Throwable x) {
```
From …
=> [JENKINS-58878] Add test that reproduces the issue

CHANGELOG.md, README.md, pom.xml
I'd like to release this plugin today, so here is a PR to migrate the wiki content to GitHub so that the changelog can be updated for the release.
=> Migrate wiki content to GitHub and add 2.21 release notes

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
See [JENKINS-60354](https://issues.jenkins-ci.org/browse/JENKINS-60354).
Downstream PRs:
* https://github.com/jenkinsci/pipeline-build-step-plugin/pull/39
* https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/102
This PR and the linked tickets are trying to solve a problem introduced by https://github.com/jenkinsci/pipeline-build-step-plugin/pull/24 that caused failures of the `build` step to be treated like build interruptions by the `retry` step, so the build failure was ignored instead of being retried. This happened because the `build` step started using `FlowInterruptedException` so that it could propagate the exact result of the downstream job instead of always propagating `FAILURE`. `FlowInterruptedException` is used for things like manual build interruptions, and so some …
=> [JENKINS-60354] Add flag to FlowInterruptedException to indicate non-interruptions

pom.xml
Should fix enforcer errors seen in the CI builds when testing against 2.222.x.
2.176.x is the fourth-oldest LTS line at this point, so I think it is safe to update.
=> Update minimum core version and parent POM to fix build errors

src/main/java/org/jenkinsci/plugins/workflow/steps/EnvironmentExpander.java
[JENKINS-63254](https://issues.jenkins-ci.org/browse/JENKINS-63254)
Enable `EnvironmentExpander` to track sensitive variables
Upstream of:
https://github.com/jenkinsci/credentials-binding-plugin/pull/105
https://github.com/jenkinsci/workflow-cps-plugin/pull/370
cc @dwnusbaum @bitwiseman
=> [JENKINS-63254][JENKINS-47101] add watch variables to EnvironmentExpander

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java, src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
See [JENKINS-51454](https://issues.jenkins.io/browse/JENKINS-51454). Upstream of jenkinsci/workflow-basic-steps-plugin#144.
=> [JENKINS-51454] Pipeline retry operation doesn't retry when there is a timeout inside of it

src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java, src/test/java/org/jenkinsci/plugins/workflow/steps/DynamicContextTest.java
I traced some test failures in https://github.com/jenkinsci/kubernetes-plugin/pull/1083 to the fact that https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 serves `Computer` instances via `DynamicContext` for the first time, and `SecretsMasker` looks up `KubernetesComputer` rather than `Computer`. This was failing because `context.get(KubernetesComputer.class)` was `null` even when `context.get(Computer.class)` would have returned an instance of `KubernetesComputer`.
=> `DynamicContext.Typed` did not correctly handle queries of subtypes

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java, src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java, src/main/java/org/jenkinsci/plugins/workflow/steps/MissingContextVariableException.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java, src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java, src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecutionTest.java, src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
=> Miscellaneous code cleanup

src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
Reduce two unnecessary usages of Guava by replacing them with native Java Platform functionality. This is intended to be a very small and non-controversial change, since it only changes an internal implementation detail and API documentation without breaking compatibility.
=> Reduce usages of Guava

src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousResumeNotSupportedException.java
Not solving https://issues.jenkins.io/browse/JENKINS-30383 as stated, but offering a well-typed marker that https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 could use to retry the entire enclosing `node` block when a synchronous step fails. This is coarser-grained and so less efficient, but might be safer in case a half-completed synchronous step left behind corrupt files or something; does not preclude a future option to directly retry the one step if it is known to be idempotent.
=> `SynchronousResumeNotSupportedException` as a marker for lack of JENKINS-30383

Jenkinsfile, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java
Similar to #17. https://github.com/jenkinsci/pipeline-input-step-plugin/pull/64#discussion_r777745911, needed for https://github.com/jenkinsci/pipeline-input-step-plugin/pull/69.
=> Allow `AbstractStepImpl` to still be subclassed for serial compatibility

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/ExceptionCause.java, src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
Follows up #51. Implemented in https://github.com/jenkinsci/workflow-cps-plugin/pull/570. https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/254 describes motivation.
=> [JENKINS-49707] Recommend `BodyExecution.cancel` overload taking `Throwable`

pom.xml, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java
Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.
=> Forward compatibility with Guice 7

src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java, src/main/java/org/jenkinsci/plugins/workflow/steps/Step.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
=> Link to `StepExecutions` in relevant Javadoc

src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java
Recent versions of `spotbugs-maven-plugin` no longer ignore `Nullable` and treat the presence of this annotation as a reason to log a new warning whenever anyone calls this method and doesn't check the result for null. Since our plugins do this in dozens of places this creates a lot of new warnings. This PR restores the old behavior by removing the `Nullable` annotation.
- `mvn clean verify -DskipTests`
- Reproduced the problem in `workflow-durable-task-step` plugin with SpotBugs 4.8.6.0; verified that after this PR most of the new warnings went away.
=> Remove `@Nullable` annotation

src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecutionIterator.java
https://github.com/jenkinsci/workflow-step-api-plugin/pull/196#pullrequestreview-2567935154 Downstream PRs coming shortly.
=> Replace `StepExecution.applyAll(Function)` with `.acceptAll(Consumer)`

src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
No need to use a third-party library when this functionality is available in the Java Platform since Java 7.
=> Migrate from Commons Lang to native Java Platform functionality
